[package]
name = "mini_grep"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
ansi_term = "0.12.1"
glob = "0.3.0"
regex = "1.1.8"